-- ============================================================
-- MIGRACAO 14: NOTIFICACOES PUSH (Web Push / VAPID)
--
-- Objetivo:
--   * Disparar notificacoes push (somente push, sem sino interno)
--     para os usuarios do app quando eventos importantes ocorrem.
--   * As "regras" de o-que-notificar sao definidas pelo ADMIN
--     (nao por usuario). Ver tabela notification_settings.
--   * Segmentar o publico por nivel de acesso (admin/vendedor/
--     instalador). Por padrao: admin recebe tudo.
--
-- Eventos suportados:
--   nova_venda          - venda finalizada
--   conta_receber       - titulos a receber vencendo hoje/atrasados
--   conta_pagar         - despesas pendentes vencendo hoje/atrasadas
--   instalacao_proxima  - instalacao agendada para hoje/amanha
--   instalacao_status   - instalacao reagendada/cancelada/concluida
--   estoque_baixo       - produto com estoque disponivel <= 10
--   folha_gerada        - folha de pagamento gerada
--   vale_lancado        - vale lancado para uma equipe
--   folha_pendente      - folha de pagamento pendente (varredura diaria)
--
-- COMO USAR:
--   1) Rode este arquivo no Supabase SQL Editor (idempotente).
--   2) Crie o segredo compartilhado no Vault (ver rodape do arquivo).
--   3) Publique a Edge Function "notify" e configure os secrets.
--
-- IMPORTANTE: toca SOMENTE tabelas publicas SEM o prefixo "jsp_".
-- ============================================================

-- ------------------------------------------------------------------
-- 0) Extensoes necessarias
-- ------------------------------------------------------------------
create extension if not exists pg_net;   -- HTTP assincrono a partir do banco
create extension if not exists pg_cron;  -- agendador (varreduras diarias)

-- ------------------------------------------------------------------
-- 1) Tabelas
-- ------------------------------------------------------------------

-- 1.1) Inscricoes push (uma por dispositivo/navegador).
create table if not exists public.push_subscriptions (
    id           bigint generated by default as identity primary key,
    user_email   text not null,
    user_id      uuid,
    endpoint     text not null unique,
    p256dh       text not null,
    auth         text not null,
    user_agent   text,
    created_at   timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_email_idx
    on public.push_subscriptions (user_email);

-- 1.2) Preferencias de notificacao (globais, definidas pelo admin).
create table if not exists public.notification_settings (
    event_key  text primary key,
    enabled    boolean not null default true,
    roles      text[]  not null default array['admin']::text[],
    updated_at timestamptz not null default now()
);

-- 1.3) Log de envio (idempotencia: nao repetir o mesmo evento/pessoa).
create table if not exists public.notification_log (
    id         bigint generated by default as identity primary key,
    event_key  text not null,
    ref_id     text not null,
    user_email text not null,
    created_at timestamptz not null default now(),
    constraint notification_log_unique unique (event_key, ref_id, user_email)
);
create index if not exists notification_log_created_at_idx
    on public.notification_log (created_at);

-- ------------------------------------------------------------------
-- 2) RLS
-- ------------------------------------------------------------------
alter table public.push_subscriptions   enable row level security;
alter table public.notification_settings enable row level security;
alter table public.notification_log      enable row level security;

-- 2.1) push_subscriptions: cada usuario so enxerga/gerencia as S SUAS inscricoes.
drop policy if exists push_subscriptions_own on public.push_subscriptions;
create policy push_subscriptions_own on public.push_subscriptions
    for all to authenticated
    using (lower(user_email) = lower(auth.jwt() ->> 'email'))
    with check (lower(user_email) = lower(auth.jwt() ->> 'email'));

-- 2.2) notification_settings: qualquer autenticado LÊ; somente admin ESCREVE.
drop policy if exists notification_settings_read on public.notification_settings;
create policy notification_settings_read on public.notification_settings
    for select to authenticated using (true);

drop policy if exists notification_settings_admin_write on public.notification_settings;
create policy notification_settings_admin_write on public.notification_settings
    for all to authenticated
    using (
        exists (
            select 1 from public.usuarios u
            where lower(u.email) = lower(auth.jwt() ->> 'email')
              and u.nivel_acesso = 'admin'
        )
    )
    with check (
        exists (
            select 1 from public.usuarios u
            where lower(u.email) = lower(auth.jwt() ->> 'email')
              and u.nivel_acesso = 'admin'
        )
    );

-- 2.3) notification_log: leitura autenticada; escrita apenas via service_role.
drop policy if exists notification_log_read on public.notification_log;
create policy notification_log_read on public.notification_log
    for select to authenticated using (true);

-- (re)garante privilegios explicitos (idempotente).
grant select, insert, update, delete on public.push_subscriptions  to authenticated;
grant select, insert, update, delete on public.notification_settings to authenticated;
grant select on public.notification_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ------------------------------------------------------------------
-- 3) Seed das preferencias (defaults sensatos; NAO sobrescreve ajustes)
-- ------------------------------------------------------------------
insert into public.notification_settings (event_key, enabled, roles) values
    ('nova_venda',         true, array['admin','vendedor']),
    ('conta_receber',      true, array['admin']),
    ('conta_pagar',        true, array['admin']),
    ('instalacao_proxima', true, array['admin','instalador']),
    ('instalacao_status',  true, array['admin','instalador']),
    ('estoque_baixo',      true, array['admin']),
    ('folha_gerada',       true, array['admin']),
    ('vale_lancado',       true, array['admin']),
    ('folha_pendente',     true, array['admin'])
on conflict (event_key) do nothing;

-- ------------------------------------------------------------------
-- 4) Schema privado + helper de disparo
-- ------------------------------------------------------------------
create schema if not exists private;

-- "hoje" no fuso do Brasil (o banco roda em UTC).
create or replace function private.hoje_brt()
returns date
language sql
stable
as $$
    select (now() at time zone 'America/Sao_Paulo')::date;
$$;

-- Envia um POST para a Edge Function "notify".
-- O segredo compartilhado fica no Vault sob o nome 'push_notify_secret'.
create or replace function private.notify(
    p_event text,
    p_ref   text,
    p_title text,
    p_body  text,
    p_url   text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_secret text;
begin
    select decrypted_secret into v_secret
      from vault.decrypted_secrets
     where name = 'push_notify_secret'
     limit 1;

    perform net.http_post(
        url := 'https://lyieiqhkspbowsrlngvn.supabase.co/functions/v1/notify',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'x-webhook-secret', coalesce(v_secret, '')
        ),
        body := jsonb_build_object(
            'event_key', p_event,
            'ref_id',    p_ref,
            'title',     p_title,
            'body',      p_body,
            'url',       coalesce(p_url, '')
        ),
        timeout_milliseconds := 8000
    );
exception
    when others then
        -- Nunca derruba a transacao de negocio por falha de notificacao.
        raise warning 'private.notify falhou: % (%)', sqlerrm, p_event;
end;
$$;

-- ------------------------------------------------------------------
-- 5) Gatilhos (tempo real)
-- ------------------------------------------------------------------

-- 5.1) Nova venda finalizada (uma linha por item em "logs").
--      Gatilho a nivel de STATEMENT: agrupa por venda (id) e envia UMA vez.
create or replace function private.tg_notify_nova_venda()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    r record;
begin
    for r in
        select id, max(cliente_nome) as cliente_nome
          from new_rows
         where tipo = 'venda' and status = 'ATIVO'
         group by id
    loop
        perform private.notify(
            'nova_venda',
            'venda:' || r.id::text,
            'Nova venda finalizada',
            format('Venda #%s - %s', r.id, coalesce(r.cliente_nome, 'Consumidor')),
            '/sistema.html'
        );
    end loop;
    return null;
end;
$$;

drop trigger if exists trg_notify_nova_venda on public.logs;
create trigger trg_notify_nova_venda
    after insert on public.logs
    referencing new table as new_rows
    for each statement
    execute function private.tg_notify_nova_venda();

-- 5.2) Agenda de instalacao (agendada p/ hoje/amanha, e mudancas de status).
create or replace function private.tg_notify_agenda()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_cliente text;
    v_quando  text;
begin
    select cliente_nome into v_cliente
      from public.mdf_orcamentos
     where id = new.orcamento_id;

    -- Agendada para hoje ou amanha.
    if new.status = 'AGENDADO'
       and new.data_agendada is not null
       and new.data_agendada in (private.hoje_brt(), private.hoje_brt() + 1) then
        v_quando := case when new.data_agendada = private.hoje_brt() then 'hoje' else 'amanha' end;
        perform private.notify(
            'instalacao_proxima',
            'agenda:' || new.id::text || ':' || new.data_agendada::text || ':proxima',
            'Instalacao agendada',
            format('Instalacao de %s marcada para %s (%s).',
                   coalesce(v_cliente, 'cliente'), v_quando,
                   to_char(new.data_agendada, 'DD/MM')),
            '/sistema.html'
        );
    end if;

    -- Mudanca de status (reagendado/cancelado/concluido).
    if tg_op = 'UPDATE'
       and new.status is distinct from old.status
       and new.status in ('REAGENDADO', 'CANCELADO', 'CONCLUIDO') then
        perform private.notify(
            'instalacao_status',
            'agenda:' || new.id::text || ':' || new.status || ':' ||
                extract(epoch from now())::bigint::text,
            'Instalacao ' || lower(new.status),
            format('Instalacao de %s: status %s.',
                   coalesce(v_cliente, 'cliente'), new.status),
            '/sistema.html'
        );
    end if;

    return new;
end;
$$;

drop trigger if exists trg_notify_agenda on public.mdf_agenda;
create trigger trg_notify_agenda
    after insert or update on public.mdf_agenda
    for each row
    execute function private.tg_notify_agenda();

-- 5.3) Estoque baixo/zerado (disponivel = fisico - comprometido).
create or replace function private.tg_notify_estoque_baixo()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_disp numeric;
begin
    v_disp := coalesce(new.estoque_fisico, 0) - coalesce(new.estoque_comprometido, 0);
    if v_disp <= 10 then
        perform private.notify(
            'estoque_baixo',
            'estoque:' || new.id::text || ':' || private.hoje_brt()::text,
            case when v_disp <= 0 then 'Produto sem estoque' else 'Estoque baixo' end,
            format('%s: %s unidade(s) disponivel(is).', new.nome, trim(to_char(v_disp, 'FM999999990.##'))),
            '/sistema.html'
        );
    end if;
    return new;
end;
$$;

drop trigger if exists trg_notify_estoque_baixo on public.produtos;
create trigger trg_notify_estoque_baixo
    after insert or update of estoque_fisico, estoque_comprometido on public.produtos
    for each row
    execute function private.tg_notify_estoque_baixo();

-- 5.4) Folha gerada.
create or replace function private.tg_notify_folha_gerada()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_equipe text;
begin
    select nome into v_equipe from public.equipe where id = new.equipe_id;
    perform private.notify(
        'folha_gerada',
        'folha:' || new.id::text,
        'Folha gerada',
        format('Folha %s da equipe %s no valor de R$ %s.',
               coalesce(new.mes_referencia, ''),
               coalesce(v_equipe, '#' || new.equipe_id::text),
               trim(to_char(coalesce(new.salario_base, 0) + coalesce(new.vales_total, 0), 'FM999999990.00'))),
        '/sistema.html'
    );
    return new;
end;
$$;

drop trigger if exists trg_notify_folha_gerada on public.folhas;
create trigger trg_notify_folha_gerada
    after insert on public.folhas
    for each row
    execute function private.tg_notify_folha_gerada();

-- 5.5) Vale lancado.
create or replace function private.tg_notify_vale_lancado()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_equipe text;
begin
    select nome into v_equipe from public.equipe where id = new.equipe_id;
    perform private.notify(
        'vale_lancado',
        'vale:' || new.id::text,
        'Vale lancado',
        format('Vale de R$ %s para %s.',
               trim(to_char(coalesce(new.valor, 0), 'FM999999990.00')),
               coalesce(v_equipe, 'equipe #' || new.equipe_id::text)),
        '/sistema.html'
    );
    return new;
end;
$$;

drop trigger if exists trg_notify_vale_lancado on public.vales;
create trigger trg_notify_vale_lancado
    after insert on public.vales
    for each row
    execute function private.tg_notify_vale_lancado();

-- ------------------------------------------------------------------
-- 6) Varreduras diarias (cron)
-- ------------------------------------------------------------------

-- 6.1) Contas a receber vencendo hoje / atrasadas.
create or replace function private.cron_scan_receber()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_hoje   integer;
    v_atras  integer;
    v_total  numeric;
begin
    select
        count(*) filter (where nullif(vencimento,'')::date = private.hoje_brt()),
        count(*) filter (where nullif(vencimento,'')::date < private.hoje_brt()),
        coalesce(sum(valor_total) filter (
            where nullif(vencimento,'')::date <= private.hoje_brt()), 0)
      into v_hoje, v_atras, v_total
      from public.logs
     where tipo in ('venda', 'receita')
       and status = 'ATIVO'
       and coalesce(status_financeiro, '') in ('A RECEBER', 'PENDENTE')
       and nullif(vencimento, '') is not null
       and nullif(vencimento, '')::date <= private.hoje_brt();

    if (v_hoje + v_atras) > 0 then
        perform private.notify(
            'conta_receber',
            'receber:' || private.hoje_brt()::text,
            'Contas a receber',
            format('%s vencendo hoje e %s atrasada(s). Total: R$ %s.',
                   v_hoje, v_atras, trim(to_char(v_total, 'FM999999990.00'))),
            '/sistema.html'
        );
    end if;
end;
$$;

-- 6.2) Contas a pagar pendentes vencendo hoje / atrasadas.
create or replace function private.cron_scan_pagar()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_hoje  integer;
    v_atras integer;
    v_total numeric;
begin
    select
        count(*) filter (where nullif(data,'')::date = private.hoje_brt()),
        count(*) filter (where nullif(data,'')::date < private.hoje_brt()),
        coalesce(sum(coalesce(custo,0) * coalesce(quantidade,1)) filter (
            where nullif(data,'')::date <= private.hoje_brt()), 0)
      into v_hoje, v_atras, v_total
      from public.despesas
     where status = 'PENDENTE'
       and nullif(data, '') is not null
       and nullif(data, '')::date <= private.hoje_brt();

    if (v_hoje + v_atras) > 0 then
        perform private.notify(
            'conta_pagar',
            'pagar:' || private.hoje_brt()::text,
            'Contas a pagar',
            format('%s vencendo hoje e %s atrasada(s). Total: R$ %s.',
                   v_hoje, v_atras, trim(to_char(v_total, 'FM999999990.00'))),
            '/sistema.html'
        );
    end if;
end;
$$;

-- 6.3) Folhas pendentes.
create or replace function private.cron_scan_folha_pendente()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_qtd integer;
begin
    select count(*) into v_qtd
      from public.folhas
     where status = 'PENDENTE';

    if v_qtd > 0 then
        perform private.notify(
            'folha_pendente',
            'folha_pend:' || private.hoje_brt()::text,
            'Folha pendente',
            format('%s folha(s) de pagamento pendente(s).', v_qtd),
            '/sistema.html'
        );
    end if;
end;
$$;

-- 6.4) Limpeza do log de idempotencia (mantem 60 dias).
create or replace function private.cron_cleanup_notification_log()
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
    delete from public.notification_log where created_at < now() - interval '60 days';
$$;

-- Agendamentos (horario em UTC). 10:00 UTC = 07:00 America/Sao_Paulo.
do $$
declare
    j text;
begin
    foreach j in array array[
        'notify_conta_receber', 'notify_conta_pagar',
        'notify_folha_pendente', 'notify_cleanup'
    ]
    loop
        if exists (select 1 from cron.job where jobname = j) then
            perform cron.unschedule(j);
        end if;
    end loop;
end;
$$;

select cron.schedule('notify_conta_receber', '0 10 * * *', $$ select private.cron_scan_receber(); $$);
select cron.schedule('notify_conta_pagar',   '0 10 * * *', $$ select private.cron_scan_pagar(); $$);
select cron.schedule('notify_folha_pendente','0 10 * * *', $$ select private.cron_scan_folha_pendente(); $$);
select cron.schedule('notify_cleanup',       '30 3 * * *', $$ select private.cron_cleanup_notification_log(); $$);

-- ============================================================
-- PASSOS MANUAIS (fora deste SQL, feitos uma unica vez):
--
--   1) Segredo compartilhado no Vault (troque pelo valor real):
--        select vault.create_secret('<SEGREDO>', 'push_notify_secret',
--                                   'Segredo do webhook de push');
--      O MESMO valor deve ser configurado como secret da Edge Function:
--        supabase secrets set WEBHOOK_SECRET=<SEGREDO> \
--          VAPID_PUBLIC_KEY=<chave publica> \
--          VAPID_PRIVATE_KEY=<chave privada> \
--          VAPID_SUBJECT=mailto:contato@gruporvjatai.com.br
--
--   2) Publique a funcao:  supabase functions deploy notify
-- ============================================================
