-- ============================================================
-- MIGRACAO 15: Tipo "servico" (nao controla estoque) + tabela de categorias
--
-- PARTE A - produtos.tipo
--   * Adiciona a coluna 'tipo' em public.produtos ('produto' | 'servico').
--   * Produtos com categoria de servico viram tipo='servico' e tem o
--     estoque zerado (nao controlam estoque).
--
-- PARTE B - categorias
--   * Cria public.categorias (cadastro/edicao pela sub-aba Produtos > Categorias).
--   * Semeia a lista padronizada e normaliza produtos.categoria
--     (remove \r\n / espacos e padroniza em CAIXA ALTA).
--
-- CUIDADO: rode primeiro o backup:
--   CREATE TABLE public.produtos_backup_YYYYMMDD AS SELECT * FROM public.produtos;
--
-- IDEMPOTENTE (pode rodar quantas vezes quiser).
-- ============================================================

-- ---------- PARTE A: tipo em produtos ----------
ALTER TABLE public.produtos ADD COLUMN IF NOT EXISTS tipo text;
UPDATE public.produtos SET tipo = 'produto' WHERE tipo IS NULL OR tipo = '';
ALTER TABLE public.produtos ALTER COLUMN tipo SET DEFAULT 'produto';
ALTER TABLE public.produtos ALTER COLUMN tipo SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.produtos'::regclass
          AND conname = 'produtos_tipo_check'
    ) THEN
        ALTER TABLE public.produtos
            ADD CONSTRAINT produtos_tipo_check CHECK (tipo IN ('produto', 'servico'));
    END IF;
END $$;

UPDATE public.produtos SET tipo = 'servico' WHERE categoria ILIKE 'servi%';
UPDATE public.produtos SET estoque_fisico = 0, estoque_comprometido = 0 WHERE tipo = 'servico';

-- ---------- PARTE B: categorias ----------
CREATE TABLE IF NOT EXISTS public.categorias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS categorias_nome_uidx ON public.categorias (upper(nome));

ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_authenticated_all ON public.categorias;
CREATE POLICY rls_authenticated_all ON public.categorias
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.categorias TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Seed padronizado (base: valores normalizados ja usados + funcionais).
INSERT INTO public.categorias (nome) VALUES
    ('MADEIRA'), ('FERRAGEM'), ('SERVIÇO'), ('PARIRI'), ('PEROBA'),
    ('GARROTE'), ('CEDRINHO'), ('FABRICAÇÃO'), ('PINUS'), ('MESCLA'),
    ('ACESSÓRIOS'), ('DIVERSOS'), ('MADERITE'), ('PALANQUE'), ('CUMARU')
ON CONFLICT DO NOTHING;

-- Normaliza categorias ja cadastradas nos produtos (remove \r\n/espacos, MAIUSCULA).
UPDATE public.produtos
   SET categoria = upper(btrim(regexp_replace(coalesce(categoria, ''), '\s+', ' ', 'g')));

-- Conferencia:
-- SELECT tipo, count(*) FROM public.produtos GROUP BY 1;
-- SELECT categoria, count(*) FROM public.produtos GROUP BY 1 ORDER BY 2 DESC;
-- SELECT * FROM public.categorias ORDER BY nome;
