-- ============================================================
-- MIGRACAO 16: Categorias de despesa por ID (nao mais texto livre)
--
-- PARTE A - public.categorias_despesas
--   * Cadastro das 20 categorias padronizadas de despesa.
--   * CRUD pela aba Financeiro > botao "Categorias" (modal).
--
-- PARTE B - despesas.categoria_id
--   * Adiciona categoria_id (FK) em public.despesas.
--   * Preenche (backfill) cada despesa existente com a categoria
--     correspondente, mapeando o texto antigo de `item`.
--   * A coluna `item` NAO e alterada (fica como historico/rollback).
--
-- CUIDADO: rode o backup ANTES:
--   CREATE TABLE public.despesas_backup_YYYYMMDD AS SELECT * FROM public.despesas;
--
-- IDEMPOTENTE (pode rodar quantas vezes quiser).
-- ============================================================

-- ---------- PARTE A: tabela de categorias de despesa ----------
CREATE TABLE IF NOT EXISTS public.categorias_despesas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS categorias_despesas_nome_uidx
    ON public.categorias_despesas (upper(nome));

ALTER TABLE public.categorias_despesas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_authenticated_all ON public.categorias_despesas;
CREATE POLICY rls_authenticated_all ON public.categorias_despesas
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.categorias_despesas TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- As 20 categorias padronizadas (lista fechada).
INSERT INTO public.categorias_despesas (nome) VALUES
    ('FORNECEDOR'),
    ('MERCADORIA'),
    ('PRÓ-LABORE'),
    ('SALÁRIO'),
    ('ENCARGOS'),
    ('ENERGIA'),
    ('ÁGUA'),
    ('INTERNET/TELEFONE'),
    ('IMPOSTOS/TAXAS'),
    ('CONTABILIDADE'),
    ('JUROS/TAXAS'),
    ('COMBUSTÍVEL'),
    ('MANUTENÇÃO DE MÁQUINAS'),
    ('VEÍCULOS/PEÇAS'),
    ('MARCENARIA/PRODUÇÃO'),
    ('INSTALAÇÃO'),
    ('ESCRITÓRIO'),
    ('ALIMENTAÇÃO'),
    ('SISTEMA/SOFTWARE'),
    ('OUTROS')
ON CONFLICT DO NOTHING;

-- ---------- PARTE B: categoria_id em despesas ----------
ALTER TABLE public.despesas ADD COLUMN IF NOT EXISTS categoria_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'despesas_categoria_id_fkey'
    ) THEN
        ALTER TABLE public.despesas
            ADD CONSTRAINT despesas_categoria_id_fkey
            FOREIGN KEY (categoria_id) REFERENCES public.categorias_despesas(id);
    END IF;
END $$;

-- Backfill idempotente: so mexe em quem ainda esta sem categoria.
WITH base AS (
    SELECT id,
           tipo_despesa,
           upper(btrim(regexp_replace(coalesce(item, ''), '\s+', ' ', 'g'))) AS n
      FROM public.despesas
     WHERE categoria_id IS NULL
),
mapeado AS (
    SELECT id,
        CASE
            WHEN tipo_despesa = 'MERCADORIA' THEN 'MERCADORIA'
            WHEN n ~ 'PROLABORE|PRÓ-LABORE|PRO-LABORE' THEN 'PRÓ-LABORE'
            WHEN n ~ 'SALAR|SALÁR|\mVALE\M' THEN 'SALÁRIO'
            WHEN n ~ 'FGTS|INSS|ENCARG|FERIAS|FÉRIAS|DECIMO|DÉCIMO|RESCISAO|RESCISÃO' THEN 'ENCARGOS'
            WHEN n ~ 'ENERGIA|LUZ|CEMAT|ENERGISA' THEN 'ENERGIA'
            WHEN n ~ 'ÁGUA|AGUA|SANEAGO|SANEAMENTO' THEN 'ÁGUA'
            WHEN n ~ 'INTERNET|TELEFONE|VIVO|CLARO|\mTIM\M' THEN 'INTERNET/TELEFONE'
            WHEN n ~ 'IMPOSTO|SIMPLES|ICMS|TRIBUT|CAPITAL CONTABILIDADE|PGFN|RBF|PARCELAMENTO|BOLETO' THEN 'IMPOSTOS/TAXAS'
            WHEN n ~ 'CONTABILIDADE|CONTADOR' THEN 'CONTABILIDADE'
            WHEN n ~ 'JUROS|TAXA|TARIFA|BANCO|STONE|MAQUININHA' THEN 'JUROS/TAXAS'
            WHEN n ~ 'COMBUST|POSTO|GASOLINA|DIESEL|ETANOL' THEN 'COMBUSTÍVEL'
            WHEN n ~ 'MANUTEN|MAQUINA|MÁQUINA|PECA|PEÇA|CORREIA|OFICINA|ELETRODO|OLEO|ÓLEO' THEN 'MANUTENÇÃO DE MÁQUINAS'
            WHEN n ~ 'VEICUL|VEÍCUL|CARRO|MOTO|PNEU' THEN 'VEÍCULOS/PEÇAS'
            WHEN n ~ 'MARCENARIA|PRODUC|PRODUÇ|AREIA|CIMENTO' THEN 'MARCENARIA/PRODUÇÃO'
            WHEN n ~ 'INSTALA|MONTAGEM|TERCEIRIZ' THEN 'INSTALAÇÃO'
            WHEN n ~ 'ESCRITORIO|ESCRITÓRIO|PAPELARIA' THEN 'ESCRITÓRIO'
            WHEN n ~ 'ALIMENTA|MERCADO|DO LAR|LANCHE|COPO|EMBALAGEM|REFEI|CAFE|CAFÉ' THEN 'ALIMENTAÇÃO'
            WHEN n ~ 'SISTEMA|SOFTWARE|CERTIFICADO|MANTO|NUVEM|ASSINATURA' THEN 'SISTEMA/SOFTWARE'
            WHEN n ~ 'FORNECEDOR|MADEIREIR|MADEIREIA|MADEREIR|MAD MACIEL|BRW|SISPORTE|PEDREIRA|SOLUFLEX|TAUARI|PINUS|COMPRA|LOJA|DISTRIBUIDORA|FERRAGEM|FECHADURA' THEN 'FORNECEDOR'
            ELSE 'OUTROS'
        END AS nome
      FROM base
)
UPDATE public.despesas d
   SET categoria_id = c.id
  FROM mapeado m
  JOIN public.categorias_despesas c ON c.nome = m.nome
 WHERE d.id = m.id;

-- Conferencia:
-- SELECT c.nome, count(d.id) AS despesas
--   FROM public.categorias_despesas c
--   LEFT JOIN public.despesas d ON d.categoria_id = c.id
--  GROUP BY c.nome ORDER BY 2 DESC, 1;
-- SELECT count(*) FROM public.despesas WHERE categoria_id IS NULL; -- deve ser 0
